export const CAMERA_ZOOM = 3;
export const RENDER_DISTANCE = 4;
export const TILE_SIZE = 16;        // Taille en pixels
export const CHUNK_SIZE = 8;       // Taille des chunks
export const MAP_FREQUENCY = 0.1;
export const KNOCKBACK_TIMER = 50;
export const ATTACK_SEQUENCE = ["ATTACK_1", "ATTACK_2"];
export const ATTACK_COOLDOWN = 25;
export const ATTACK_RESET = 60;
export const TP_COOLDOWN = 120;
export const TP_DISTANCE = 120;