export const CAMERA_ZOOM = 3;
export const RENDER_DISTANCE = 4;
export const TILE_SIZE = 16;        // Taille en pixels
export const CHUNK_SIZE = 8;       // Taille des chunks
export const MAP_FREQUENCY = 0.1;
export const KNOCKBACK_TIMER = 40;
export const ATTACK_COOLDOWN = 25;
export const ATTACK_RESET = 100;
export const TP_COOLDOWN = 120;
export const TP_DISTANCE = 120;
export const DASH_ATTACK_DURATION = 30;
export const BLOCK_DURATION = 30;
export const BLOCK_COOLDOWN = 30;