export enum ServerToSocketMsg {
    CONNECTED = "CONNECTED",
    CURRENT_PLAYERS = "CURRENT_PLAYERS",
    NEW_PLAYER = "NEW_PLAYER",
    PLAYER_UPDATE = "PLAYER_UPDATE",
    START_ATTACK = "START_ATTACK",
    ATTACK = "ATTACK",
    ATTACK_RESULT = "ATTACK_RESULT",
    DISCONNECT = "DISCONNECT",
    PLAYER_DIED = "PLAYER_DIED",
    PLAYER_RESPAWNED = "PLAYER_RESPAWNED",
    PLAYER_POS_UPDATE = "PLAYER_POS_UPDATE",
    PLAYER_DIRECTION_UPDATE = "PLAYER_DIRECTION_UPDATE",
    PLAYER_PROGRESSED = "PLAYER_PROGRESSED"
}